/*
 * explore-api
 * The Opendatasoft Explore API v2 is organized around REST. It provides access to all the data available through the platform in a coherent, hierarchical way.  - Only the HTTP `GET` method is supported. - All API endpoints return JSON. - Endpoints are organized in a hierarchical way describing the relative relationship between objects. - All responses contain a list of links allowing easy and relevant navigation through the API endpoints. - All endpoints use the [Opendatasoft Query Language (ODSQL)](https://help.opendatasoft.com/apis/ods-explore-v2/#section/Opendatasoft-Query-Language-(ODSQL)). This means that, most of the time, parameters work the same way for all endpoints. - While the `records` endpoint is subject to a [limited number of returned records](https://help.opendatasoft.com/apis/ods-explore-v2/#tag/Dataset/operation/getRecords), the `exports` endpoint has no limitations.
 *
 * The version of the OpenAPI document: v2.1
 * Contact: support@opendatasoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.wso2.client.model.explore_api;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InlineResponse429
 */
public class InlineResponse429Test {
    private final InlineResponse429 model = new InlineResponse429();

    /**
     * Model tests for InlineResponse429
     */
    @Test
    public void testInlineResponse429() {
        // TODO: test InlineResponse429
    }

    /**
     * Test the property 'errorcode'
     */
    @Test
    public void errorcodeTest() {
        // TODO: test errorcode
    }

    /**
     * Test the property 'resetTime'
     */
    @Test
    public void resetTimeTest() {
        // TODO: test resetTime
    }

    /**
     * Test the property 'limitTimeUnit'
     */
    @Test
    public void limitTimeUnitTest() {
        // TODO: test limitTimeUnit
    }

    /**
     * Test the property 'callLimit'
     */
    @Test
    public void callLimitTest() {
        // TODO: test callLimit
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

}
