/*
 * explore-api
 * The Opendatasoft Explore API v2 is organized around REST. It provides access to all the data available through the platform in a coherent, hierarchical way.  - Only the HTTP `GET` method is supported. - All API endpoints return JSON. - Endpoints are organized in a hierarchical way describing the relative relationship between objects. - All responses contain a list of links allowing easy and relevant navigation through the API endpoints. - All endpoints use the [Opendatasoft Query Language (ODSQL)](https://help.opendatasoft.com/apis/ods-explore-v2/#section/Opendatasoft-Query-Language-(ODSQL)). This means that, most of the time, parameters work the same way for all endpoints. - While the `records` endpoint is subject to a [limited number of returned records](https://help.opendatasoft.com/apis/ods-explore-v2/#tag/Dataset/operation/getRecords), the `exports` endpoint has no limitations.
 *
 * The version of the OpenAPI document: v2.1
 * Contact: support@opendatasoft.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.wso2.client.model.explore_api;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * InlineResponse429
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-08-07T09:20:08.114975Z[GMT]")
public class InlineResponse429 {
  public static final String SERIALIZED_NAME_ERRORCODE = "errorcode";
  @SerializedName(SERIALIZED_NAME_ERRORCODE)
  private BigDecimal errorcode;

  public static final String SERIALIZED_NAME_RESET_TIME = "reset_time";
  @SerializedName(SERIALIZED_NAME_RESET_TIME)
  private String resetTime;

  public static final String SERIALIZED_NAME_LIMIT_TIME_UNIT = "limit_time_unit";
  @SerializedName(SERIALIZED_NAME_LIMIT_TIME_UNIT)
  private String limitTimeUnit;

  public static final String SERIALIZED_NAME_CALL_LIMIT = "call_limit";
  @SerializedName(SERIALIZED_NAME_CALL_LIMIT)
  private BigDecimal callLimit;

  public static final String SERIALIZED_NAME_ERROR = "error";
  @SerializedName(SERIALIZED_NAME_ERROR)
  private String error;

  public InlineResponse429() { 
  }

  public InlineResponse429 errorcode(BigDecimal errorcode) {
    
    this.errorcode = errorcode;
    return this;
  }

   /**
   * Get errorcode
   * @return errorcode
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getErrorcode() {
    return errorcode;
  }


  public void setErrorcode(BigDecimal errorcode) {
    this.errorcode = errorcode;
  }


  public InlineResponse429 resetTime(String resetTime) {
    
    this.resetTime = resetTime;
    return this;
  }

   /**
   * Get resetTime
   * @return resetTime
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getResetTime() {
    return resetTime;
  }


  public void setResetTime(String resetTime) {
    this.resetTime = resetTime;
  }


  public InlineResponse429 limitTimeUnit(String limitTimeUnit) {
    
    this.limitTimeUnit = limitTimeUnit;
    return this;
  }

   /**
   * Get limitTimeUnit
   * @return limitTimeUnit
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getLimitTimeUnit() {
    return limitTimeUnit;
  }


  public void setLimitTimeUnit(String limitTimeUnit) {
    this.limitTimeUnit = limitTimeUnit;
  }


  public InlineResponse429 callLimit(BigDecimal callLimit) {
    
    this.callLimit = callLimit;
    return this;
  }

   /**
   * Get callLimit
   * @return callLimit
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getCallLimit() {
    return callLimit;
  }


  public void setCallLimit(BigDecimal callLimit) {
    this.callLimit = callLimit;
  }


  public InlineResponse429 error(String error) {
    
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getError() {
    return error;
  }


  public void setError(String error) {
    this.error = error;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse429 inlineResponse429 = (InlineResponse429) o;
    return Objects.equals(this.errorcode, inlineResponse429.errorcode) &&
        Objects.equals(this.resetTime, inlineResponse429.resetTime) &&
        Objects.equals(this.limitTimeUnit, inlineResponse429.limitTimeUnit) &&
        Objects.equals(this.callLimit, inlineResponse429.callLimit) &&
        Objects.equals(this.error, inlineResponse429.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorcode, resetTime, limitTimeUnit, callLimit, error);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse429 {\n");
    sb.append("    errorcode: ").append(toIndentedString(errorcode)).append("\n");
    sb.append("    resetTime: ").append(toIndentedString(resetTime)).append("\n");
    sb.append("    limitTimeUnit: ").append(toIndentedString(limitTimeUnit)).append("\n");
    sb.append("    callLimit: ").append(toIndentedString(callLimit)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

